services:
  api:
    build: .
    container_name: taskflow-api

    ports:
      - "5000:5000"

    environment:
      NODE_ENV: ${NODE_ENV}
      MONGODB_URL: ${MONGODB_URL}
      REDIS_URL: ${REDIS_URL}

    depends_on:
      mongo:
        condition: service_healthy

      redis:
        condition: service_healthy

    networks:
      - taskflow-network

  mongo:
    image: mongo
    container_name: taskflow-mongo

    volumes:
      - taskflow-mongo:/data/db

    networks:
      - taskflow-network

    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:alpine
    container_name: taskflow-redis

    networks:
      - taskflow-network

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  taskflow-mongo:

networks:
  taskflow-network:
